---
name: Repository dispatch receive

on:
  repository_dispatch:
    types: [dispatch-test]

jobs:
  receive-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Receive
        run: |
          message=${{ github.event.client_payload.message }}
          echo "message from other repo = $message"
